package com.autowash.backend.customer.service.impl;

import com.autowash.backend.customer.dto.AdminCreateCustomerRequestDTO;
import com.autowash.backend.customer.dto.AdminCreateCustomerResponseDTO;
import com.autowash.backend.customer.dto.CustomerProfileResponse;
import com.autowash.backend.customer.dto.CustomerUpdateRequest;
import com.autowash.backend.common.exception.BusinessException;
import com.autowash.backend.customer.entity.Customer;
import com.autowash.backend.customer.repository.CustomerRepository;
import com.autowash.backend.customer.service.CustomerService;
import com.autowash.backend.user.entity.User;
import com.autowash.backend.user.repository.UserRepository;
import org.springframework.http.HttpStatus;
import lombok.RequiredArgsConstructor;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.util.List;

import java.util.UUID;

@Service
@RequiredArgsConstructor
public class CustomerServiceImpl implements CustomerService {

    private final CustomerRepository customerRepository;
    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;

    @Override
    public CustomerProfileResponse getCustomerProfile(Integer userId) {
        Customer customer = customerRepository.findByUser_Id(userId)  // ← fix
                .orElseThrow(() -> new BusinessException("Không tìm thấy khách hàng", HttpStatus.NOT_FOUND));
        return mapToResponse(customer);
    }

    @Override
    @Transactional
    public CustomerProfileResponse updateCustomerProfile(Integer userId, CustomerUpdateRequest request) {
        Customer customer = customerRepository.findByUser_Id(userId)  // ← fix
                .orElseThrow(() -> new BusinessException("Không tìm thấy khách hàng", HttpStatus.NOT_FOUND));

        customer.setFullName(request.getFullName());
        customer.setDateOfBirth(request.getDateOfBirth());
        customer.setGender(translateGenderToEnglish(request.getGender()));

        // Cập nhật số điện thoại và email của User liên kết
        if (customer.getUser() != null) {
            customer.getUser().setPhone(request.getPhone());
            customer.getUser().setEmail(request.getEmail());
        }

        Customer updateCustomer = customerRepository.save(customer);
        return mapToResponse(updateCustomer);
    }
    @Override
    public List<CustomerProfileResponse> getAllCustomers() {
        return customerRepository.findAll()
                .stream()
                .map(this::mapToResponse)
                .toList();
    }

    /**
     * STAFF/ADMIN tạo tài khoản khách hàng hộ.
     * Tạo đồng thời User (tài khoản đăng nhập) + Customer (hồ sơ khách hàng).
     * Không yêu cầu xác minh OTP vì nhân viên đã xác minh trực tiếp với khách.
     */
    @Override
    @Transactional
    public AdminCreateCustomerResponseDTO createCustomerByStaff(AdminCreateCustomerRequestDTO request) {
        String normalizedEmail = request.getEmail().trim().toLowerCase();
        String normalizedUsername = request.getUsername().trim();
        String normalizedPhone = normalizePhone(request.getPhone());

        if (userRepository.existsByEmail(normalizedEmail)) {
            throw new BusinessException("Email '" + normalizedEmail + "' đã được sử dụng", HttpStatus.CONFLICT);
        }
        if (userRepository.existsByUsername(normalizedUsername)) {
            throw new BusinessException("Tài khoản '" + normalizedUsername + "' đã được sử dụng", HttpStatus.CONFLICT);
        }
        if (userRepository.existsByPhone(normalizedPhone)) {
            throw new BusinessException("Số điện thoại '" + normalizedPhone + "' đã được sử dụng", HttpStatus.CONFLICT);
        }

        // Nếu nhân viên không nhập password thì tự sinh ngẫu nhiên để trả về 1 lần
        boolean autoGenerated = request.getPassword() == null || request.getPassword().isBlank();
        String rawPassword = autoGenerated
                ? UUID.randomUUID().toString().replace("-", "").substring(0, 10)
                : request.getPassword();

        User newUser = User.builder()
                .username(normalizedUsername)
                .email(normalizedEmail)
                .password(passwordEncoder.encode(rawPassword))
                .phone(normalizedPhone)
                .role("customer")
                .status("active")
                .build();
        User savedUser = userRepository.save(newUser);

        Customer newCustomer = Customer.builder()
                .user(savedUser)
                .fullName(request.getFullName().trim())
                .dateOfBirth(request.getDateOfBirth())
                .gender(translateGenderToEnglish(request.getGender()))
                .tierId(1)
                .build();
        Customer savedCustomer = customerRepository.save(newCustomer);
        // totalPoints/totalVisits/totalSpending/joinedAt là cột insertable=false (DB tự set default)
        // → load lại để response có giá trị đúng thay vì null.
        savedCustomer = customerRepository.findById(savedCustomer.getCustomerId()).orElse(savedCustomer);

        return AdminCreateCustomerResponseDTO.builder()
                .customer(mapToResponse(savedCustomer))
                .generatedPassword(autoGenerated ? rawPassword : null)
                .build();
    }

    /** Chuẩn hoá số điện thoại VN dạng 0xxxxxxxxx -> +84xxxxxxxxx, giống AuthServiceImpl. */
    private String normalizePhone(String phone) {
        String trimmed = phone == null ? "" : phone.trim();
        if (trimmed.startsWith("0") && trimmed.length() == 10) {
            return "+84" + trimmed.substring(1);
        }
        return trimmed;
    }

    private CustomerProfileResponse mapToResponse(Customer customer) {
    return CustomerProfileResponse.builder()
            .customerId(customer.getCustomerId())
            .username(customer.getUser() != null ? customer.getUser().getUsername() : null)
            .email(customer.getUser() != null ? customer.getUser().getEmail() : null)
            .phone(customer.getUser() != null ? customer.getUser().getPhone() : null)
            .fullName(customer.getFullName())
            .dateOfBirth(customer.getDateOfBirth())
            .gender(translateGenderToVietnamese(customer.getGender()))
            .totalPoints(customer.getTotalPoints())
            .totalVisits(customer.getTotalVisits())
            .totalSpending(customer.getTotalSpending())
            .tierId(customer.getTierId())
            .joinedAt(customer.getJoinedAt())
            .build();
    }
    private String translateGenderToEnglish(String gender) {
        if (gender == null) return null;
        if ("Nam".equalsIgnoreCase(gender)) return "male";
        if ("Nữ".equalsIgnoreCase(gender)) return "female";
        if ("Khác".equalsIgnoreCase(gender)) return "other";
        return gender;
    }

    private String translateGenderToVietnamese(String gender) {
        if (gender == null) return null;
        if ("male".equalsIgnoreCase(gender)) return "Nam";
        if ("female".equalsIgnoreCase(gender)) return "Nữ";
        if ("other".equalsIgnoreCase(gender)) return "Khác";
        return gender;
    }
}