### -2. GỬI MÃ OTP (Mở tab Run/Console của IntelliJ để lấy mã nhé)
POST http://localhost:8080/api/v1/auth/send-otp
Content-Type: application/json

{
  "phone": "0912345678"
}

### -1. XÁC MINH MÃ OTP (Thay số 123456 bằng mã 6 số bạn thấy trong Console)
POST http://localhost:8080/api/v1/auth/verify-otp
Content-Type: application/json

{
  "phone": "0912345678",
  "otp": "293578"
}

### 0A. ĐĂNG KÝ KHÁCH HÀNG MỚI (Bắt buộc phone phải giống ở trên)
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "username": "khachhang_vip",
  "email": "khachhangvip@gmail.com",
  "password": "password",
  "fullName": "Khách Hàng Xịn",
  "phone": "0912345678"
}

### 0B. ĐĂNG NHẬP LẤY TOKEN (Của khách hàng vừa tạo)
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "khachhang_vip", 
  "password": "password"
}

> {%
    client.global.set("auth_token", response.body.data.accessToken);
%}

### 1. LẤY PROFILE CỦA TÔI
GET http://localhost:8080/api/v1/customers/me
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### 2. CẬP NHẬT PROFILE CỦA TÔI
PUT http://localhost:8080/api/v1/customers/me
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "fullName": "Nguyễn Văn Duy",
  "dateOfBirth": "2000-01-01",
  "gender": "male"
}

### 3. THÊM XE MỚI
POST http://localhost:8080/api/v1/vehicles
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "licensePlate": "30A-12345",
  "brand": "Toyota",
  "model": "Camry",
  "vehicleType": "car",
  "color": "Black",
  "nickname": "Xe đi làm"
}

### 4. LẤY DANH SÁCH XE
GET http://localhost:8080/api/v1/vehicles
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### 5. CẬP NHẬT XE (Thay số 1 ở cuối bằng vehicleId thực tế)
PUT http://localhost:8080/api/v1/vehicles/165
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "licensePlate": "30A-12345",
  "brand": "Toyota",
  "model": "Camry 2.0",
  "vehicleType": "car",
  "color": "White",
  "nickname": "Đổi màu rồi"
}

### 6. XÓA XE (Soft Delete)
DELETE http://localhost:8080/api/v1/vehicles/165
Authorization: Bearer {{auth_token}}
